### ISSUE TITLE
Problem creating a user account to try Deep Learning Studio Personal Edition

### ISSUE THREAD

**Issue by kjancsi** [DeepCognition/deep-learning-studio#3]
"Sign up for an user account at deepcognition to start using deep learning studio"
There's no FREE or PERSONAL EDITION plan on the registration page, only STANDARD and PREMIUM plans can be selected. How do I sign up for a user account to use the free, Personal Edition?
Thanks.

**Comment by Auhill** [comment]
+1. I also have this issue.

**Comment by rajendra2** [comment]
Thanks for bringing this up. Yes, because of recent plan changes on deepcognition.ai, a free plan is no longer offered.

We will look into enabling a free plan for personal edition soon. I will notify as soon as it is implemented.
