### ISSUE TITLE
Internal Server Error in Web Browser.

### ISSUE THREAD

**Issue by softgearko** [DeepCognition/deep-learning-studio#4]
I think deep-learning-studio is excellent.
However, I encountered "Internal Server Error" in my web browser after dls.sh ~ start.
I installed everything (docker, nvidia-docker)  according to README.md 
Whenever I open the web page in the web browser, I got  "Internal Server Error" dialog box in the browser.

![image](https://user-images.githubusercontent.com/525186/30997464-03eb0796-a503-11e7-8537-1aaa5ff64b00.png)

The console displayed the following.

```
softgear@lobe:~/DeepCognition_deep-learning-studio/deep-learning-studio$ ./dls.sh -p 8080 -d /home/softgear/work/energy-consume-data start
Updating...
latest: Pulling from deepcognition/deep-learning-studio
Digest: sha256:d3e4813493dcdab089a8bdd12cdd5dfec2ac523293915c6dd4184a9c61ab657c
Status: Image is up to date for deepcognition/deep-learning-studio:latest
deep-learning-studio
Starting...
cf7ef5e59086738e775c9da525cf669398ea8a5f28495ba12a853a309d3c5159
Done

Go to http://127.0.0.1:8080/app/ to start using Deep Learning Studio
softgear@lobe:~/DeepCognition_deep-learning-studio/deep-learning-studio$

```

I want to know/debug why internal server error was occurred but there is no information about this. Is there the way to see the log file?

**Comment by rajendra2** [comment]
You can run following command to see the logs:

docker logs -f deep-learning-studio
